### ISSUE TITLE
Critical Worker Timeout for large STAC

### ISSUE THREAD

**Issue by sjordan29** [xpublish-experiments/Catalog-To-Xpublish#15]
The `xpublish-builder` starts to fail once the USGS STAC gets to be of a certain size (at this commit in the history of the STAC): [STAC](https://code.usgs.gov/wma/nhgf/stac/-/commit/2487c06878fa6cd859f1cc9c0600d7fdfa3b41cf) with the following:

```
cat_to_xpub  | [2024-04-24T12:38:49] INFO - Spinning up server from stac catalog at https://code.usgs.gov/wma/nhgf/stac/-/raw/2487c06878fa6cd859f1cc9c0600d7fdfa3b41cf/catalog/catalog.json.
cat_to_xpub  | [2024-04-24 12:39:15 -0400] [10] [CRITICAL] WORKER TIMEOUT (pid:12)
cat_to_xpub  | [2024-04-24 12:39:15 -0400] [10] [ERROR] Worker (pid:12) was sent SIGABRT!
cat_to_xpub  | [2024-04-24 12:39:15 -0400] [20] [INFO] Booting worker with pid: 20
```

@ptomasula, I'm thinking this might have to do with the architecture of mounting sub-applications in the `create_app` function? I remember you had some ideas of changing this to use routers -- or something like that. Do you think that could be the problem? Let me know how you want to tackle this - whether it's easier for you to work on this, or if you send me some resources about the expected approach I could take a crack at it.

**Comment by ptomasula** [comment]
Hey @sjordan29, I'm finally working on this. I tried using the `xpublish-builder` image and referencing [this catalog json file](https://code.usgs.gov/wma/nhgf/stac/-/blob/2487c06878fa6cd859f1cc9c0600d7fdfa3b41cf/catalog/catalog.json)  (which I believe is the one from the commit you reference above). I'm getting a bit of a different error related to parsing that json. So I'm not even hitting that timeout error.

```
xpublish-builder  |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
xpublish-builder  |   File "/opt/app/build.py", line 26, in <module>
xpublish-builder  |     app = catalog_to_xpublish.create_app(
xpublish-builder  |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
xpublish-builder  |   File "/mambaforge/lib/python3.11/site-packages/catalog_to_xpublish/server_functions.py", line 133, in create_app
xpublish-builder  |     catalog_endpoints: List[CatalogEndpoint] = catalog_searcher.parse_catalog()
xpublish-builder  |                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
xpublish-builder  |   File "/mambaforge/lib/python3.11/site-packages/catalog_to_xpublish/searchers/stac_search.py", line 133, in parse_catalog
xpublish-builder  |     catalog = self.catalog_object
xpublish-builder  |               ^^^^^^^^^^^^^^^^^^^
xpublish-builder  |   File "/mambaforge/lib/python3.11/site-packages/catalog_to_xpublish/searchers/stac_search.py", line 98, in catalog_object
xpublish-builder  |     self.__catalog_obj = pystac.Catalog.from_file(
xpublish-builder  |                          ^^^^^^^^^^^^^^^^^^^^^^^^^
xpublish-builder  |   File "/mambaforge/lib/python3.11/site-packages/pystac/catalog.py", line 1273, in from_file
xpublish-builder  |     result = super().from_file(href, stac_io)
xpublish-builder  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
xpublish-builder  |   File "/mambaforge/lib/python3.11/site-packages/pystac/stac_object.py", line 629, in from_file
xpublish-builder  |     d = stac_io.read_json(href)
xpublish-builder  |         ^^^^^^^^^^^^^^^^^^^^^^^
xpublish-builder  |   File "/mambaforge/lib/python3.11/site-packages/pystac/stac_io.py", line 206, in read_json
xpublish-builder  |     return self.json_loads(txt)
xpublish-builder  |            ^^^^^^^^^^^^^^^^^^^^
xpublish-builder  |   File "/mambaforge/lib/python3.11/site-packages/pystac/stac_io.py", line 108, in json_loads
xpublish-builder  |     result = orjson.loads(txt)
xpublish-builder  |              ^^^^^^^^^^^^^^^^^
xpublish-builder  | orjson.JSONDecodeError: unexpected character: line 6 column 1 (char 5)
xpublish-builder  | [2024-05-30 12:34:36 -0400] [12] [INFO] Worker exiting (pid: 12)
xpublish-builder  | [2024-05-30 12:34:36 -0400] [10] [ERROR] Worker (pid:12) exited with code 3
xpublish-builder  | [2024-05-30 12:34:36 -0400] [10] [ERROR] Shutting down: Master
xpublish-builder  | [2024-05-30 12:34:36 -0400] [10] [ERROR] Reason: Worker failed to boot.
```
At a glance it seems like the json file might have some formatting issues; I'll try again with a few other catalog json files, but figured I would ping you incase you have any immediate insights into what might be wrong.

**Comment by sjordan29** [comment]
Did you change the link to https://code.usgs.gov/wma/nhgf/stac/-/raw/2487c06878fa6cd859f1cc9c0600d7fdfa3b41cf/catalog/catalog.json?

Note `raw` in the url in place of `blob`

**Comment by ptomasula** [comment]
> Did you change the link to https://code.usgs.gov/wma/nhgf/stac/-/raw/2487c06878fa6cd859f1cc9c0600d7fdfa3b41cf/catalog/catalog.json?
> 
> Note `raw` in the url in place of `blob`

Ah that was it! Thanks @sjordan29, you saved me from an unnecessary rabbit hole!

**Comment by ptomasula** [comment]
That bad news is that now I was able to start a container referencing that [catalog](https://code.usgs.gov/wma/nhgf/stac/-/raw/2487c06878fa6cd859f1cc9c0600d7fdfa3b41cf/catalog/catalog.json) without issue. Is it maybe worth trying this on QA again and seeing if the problem persists?

```
publish-builder  | [2024-05-30T14:41:36] INFO - Spinning up server from stac catalog at https://code.usgs.gov/wma/nhgf/stac/-/raw/2487c06878fa6cd859f1cc9c0600d7fdfa3b41cf/catalog/catalog.json.
xpublish-builder  | [2024-05-30T14:41:58] INFO - Mounting a Xpublish server @ /conus404-daily to the main application.
xpublish-builder  | [2024-05-30T14:41:58] INFO - Mounting a Xpublish server @ /alaska_et_2020_ccsm4_historical_simulation to the main application.
xpublish-builder  | [2024-05-30T14:41:58] INFO - Mounting a Xpublish server @ /alaska_et_2020_era-interim_reanalysis to the main application.
xpublish-builder  | [2024-05-30T14:41:58] INFO - Mounting a Xpublish server @ /alaska_et_2020_gfdl_historical_simulation to the main application.
xpublish-builder  | [2024-05-30T14:41:58] INFO - Mounting a Xpublish server @ /cprep_tasmax_day_I35txdetrp1-DeltaSD-A12L01K00_rcp26_r6i1p1_I35Land_20060101-20991231 to the main application.
xpublish-builder  | [2024-05-30T14:41:58] INFO - Mounting a Xpublish server @ /macav2_historical_daily to the main application.
xpublish-builder  | [2024-05-30T14:41:58] INFO - Mounting a Xpublish server @ /macav2_historical_monthly to the main application.
xpublish-builder  | [2024-05-30T14:41:58] INFO - Mounting a Xpublish server @ /macav2_future_monthly to the main application.
xpublish-builder  | [2024-05-30T14:41:58] INFO - Mounting a Xpublish server @ /macav2_future_daily to the main application.
xpublish-builder  | [2024-05-30T14:41:58] INFO - Mounting a Xpublish server @ /maca_vic_past to the main application.
xpublish-builder  | [2024-05-30T14:41:58] INFO - Mounting a Xpublish server @ /maca_vic_future to the main application.
xpublish-builder  | [2024-05-30T14:41:58] INFO - Mounting a Xpublish server @ /LOCA_future to the main application.
xpublish-builder  | [2024-05-30T14:41:58] INFO - Mounting a Xpublish server @ /LOCA_historical to the main application.
xpublish-builder  | [2024-05-30T14:41:58] INFO - Mounting a Xpublish server @ /Red_River_future to the main application.
xpublish-builder  | [2024-05-30T14:41:58] INFO - Mounting a Xpublish server @ /Red_River_historical to the main application.
xpublish-builder  | [2024-05-30T14:41:58] INFO - Mounting a Xpublish server @ /Red_River_MPI-ESM-LR_future to the main application.
xpublish-builder  | [2024-05-30T14:41:58] INFO - Mounting a Xpublish server @ /Red_River_MPI-ESM-LR_historical to the main application.
xpublish-builder  | [2024-05-30T14:41:58] INFO - Mounting a Xpublish server @ /TTU_2019_rcp45_gridded_annual to the main application.
xpublish-builder  | [2024-05-30T14:41:58] INFO - Mounting a Xpublish server @ /TTU_2019_rcp85_gridded_annual to the main application.
xpublish-builder  | [2024-05-30T14:41:58] INFO - Mounting a Xpublish server @ /TTU_2019_rcp45_time_slices to the main application.
xpublish-builder  | [2024-05-30T14:41:58] INFO - Mounting a Xpublish server @ /TTU_2019_rcp85_time_slices to the main application.
xpublish-builder  | [2024-05-30T14:41:58] INFO - Mounting a Xpublish server @ /ssebopeta_yearly to the main application.
xpublish-builder  | [2024-05-30T14:41:58] INFO - Mounting a Xpublish server @ /ssebopeta_monthly to the main application.
xpublish-builder  | [2024-05-30T14:41:58] INFO - Mounting a Xpublish server @ /iclus_hc to the main application.
xpublish-builder  | [2024-05-30T14:41:58] INFO - Mounting a Xpublish server @ /CooperMcKenzie to the main application.
xpublish-builder  | [2024-05-30T14:41:58] INFO - Mounting a Xpublish server @ /CooperUpperDeschutes to the main application.
xpublish-builder  | [2024-05-30T14:41:58] INFO - Mounting a Xpublish server @ /TTU_2019_rcp45_station_data to the main application.
xpublish-builder  | [2024-05-30T14:41:58] INFO - Mounting a Xpublish server @ /TTU_2019_rcp85_station_data to the main application.
xpublish-builder  | [2024-05-30T14:41:58] INFO - Mounting a Xpublish server @ /bcsd_mon_vic to the main application.
xpublish-builder  | [2024-05-30T14:41:59] INFO - Mounting a Xpublish server @ /GMO to the main application.
xpublish-builder  | [2024-05-30T14:41:59] INFO - Mounting a Xpublish server @ /GMO_New to the main application.
xpublish-builder  | [2024-05-30T14:41:59] INFO - Mounting a Xpublish server @ /PRISM to the main application.
xpublish-builder  | [2024-05-30T14:41:59] INFO - Mounting a Xpublish server @ /PRISM_v2 to the main application.
xpublish-builder  | [2024-05-30T14:41:59] INFO - Mounting a Xpublish server @ /UofIMETDATA to the main application.
xpublish-builder  | [2024-05-30T14:41:59] INFO - Mounting a Xpublish server @ /bcsd_obs to the main application.
xpublish-builder  | [2024-05-30T14:41:59] INFO - Mounting a Xpublish server @ /maurer to the main application.
xpublish-builder  | [2024-05-30T14:41:59] INFO - Mounting a Xpublish server @ /farnsworth_evaporation_atlas to the main application.
xpublish-builder  | [2024-05-30T14:41:59] INFO - Mounting a Xpublish server @ /nrel_solar_radiation to the main application.
xpublish-builder  | [2024-05-30T14:41:59] INFO - Mounting a Xpublish server @ /slr2d to the main application.
xpublish-builder  | [2024-05-30T14:41:59] INFO - Mounting a Xpublish server @ /topowx to the main application.
xpublish-builder  | [2024-05-30T14:41:59] INFO - Mounting a Xpublish server @ /topowx_monthly to the main application.
xpublish-builder  | [2024-05-30T14:41:59] INFO - Mounting a Xpublish server @ /topowx_normals to the main application.
xpublish-builder  | [2024-05-30T14:41:59] INFO - Returning successfully created server application!
xpublish-builder  | [2024-05-30 14:41:59 -0400] [12] [INFO] Started server process [12]
xpublish-builder  | [2024-05-30 14:41:59 -0400] [12] [INFO] Waiting for application startup.
xpublish-builder  | [2024-05-30 14:41:59 -0400] [12] [INFO] Application startup complete.
```

**Comment by sjordan29** [comment]
Looks like that commit now works for me now too, but if I try with the entire STAC [catalog](https://code.usgs.gov/wma/nhgf/stac/-/raw/main/catalog/catalog.json), then I get the critical worker timeout error again. It just keeps trying after it fails:

```
cat_to_xpub  | [2024-05-30T15:10:40] INFO - Spinning up server from stac catalog at https://code.usgs.gov/wma/nhgf/stac/-/raw/main/catalog/catalog.json.
cat_to_xpub  | [2024-05-30 15:11:09 -0400] [10] [CRITICAL] WORKER TIMEOUT (pid:12)
cat_to_xpub  | [2024-05-30 15:11:09 -0400] [10] [ERROR] Worker (pid:12) was sent SIGABRT!
cat_to_xpub  | [2024-05-30 15:11:09 -0400] [21] [INFO] Booting worker with pid: 21
cat_to_xpub  | [2024-05-30T15:11:10] INFO - Spinning up server from stac catalog at https://code.usgs.gov/wma/nhgf/stac/-/raw/main/catalog/catalog.json.
cat_to_xpub  | [2024-05-30 15:11:39 -0400] [10] [CRITICAL] WORKER TIMEOUT (pid:21)
cat_to_xpub  | [2024-05-30 15:11:39 -0400] [10] [ERROR] Worker (pid:21) was sent SIGABRT!
cat_to_xpub  | [2024-05-30 15:11:39 -0400] [30] [INFO] Booting worker with pid: 30
cat_to_xpub  | [2024-05-30T15:11:40] INFO - Spinning up server from stac catalog at https://code.usgs.gov/wma/nhgf/stac/-/raw/main/catalog/catalog.json.
```

**Comment by ptomasula** [comment]
> Looks like that commit now works for me now too, but if I try with the entire STAC [catalog](https://code.usgs.gov/wma/nhgf/stac/-/raw/main/catalog/catalog.json), then I get the critical worker timeout error again. It just keeps trying after it fails:
> 
> ```
> cat_to_xpub  | [2024-05-30T15:10:40] INFO - Spinning up server from stac catalog at https://code.usgs.gov/wma/nhgf/stac/-/raw/main/catalog/catalog.json.
> cat_to_xpub  | [2024-05-30 15:11:09 -0400] [10] [CRITICAL] WORKER TIMEOUT (pid:12)
> cat_to_xpub  | [2024-05-30 15:11:09 -0400] [10] [ERROR] Worker (pid:12) was sent SIGABRT!
> cat_to_xpub  | [2024-05-30 15:11:09 -0400] [21] [INFO] Booting worker with pid: 21
> cat_to_xpub  | [2024-05-30T15:11:10] INFO - Spinning up server from stac catalog at https://code.usgs.gov/wma/nhgf/stac/-/raw/main/catalog/catalog.json.
> cat_to_xpub  | [2024-05-30 15:11:39 -0400] [10] [CRITICAL] WORKER TIMEOUT (pid:21)
> cat_to_xpub  | [2024-05-30 15:11:39 -0400] [10] [ERROR] Worker (pid:21) was sent SIGABRT!
> cat_to_xpub  | [2024-05-30 15:11:39 -0400] [30] [INFO] Booting worker with pid: 30
> cat_to_xpub  | [2024-05-30T15:11:40] INFO - Spinning up server from stac catalog at https://code.usgs.gov/wma/nhgf/stac/-/raw/main/catalog/catalog.json.
> ```

Confirming that I get the same behavior when I try with the entire STAC as well.

**Comment by ptomasula** [comment]
@sjordan29, I did a little more digging and it appears unrelated to the mounting of sub-applications (at least not yet, as the code hasn't even hit that block). 

My initial assessment is that the [`catalog_searcher.parse_catalog` invocation in create_app](https://github.com/xpublish-experiments/Catalog-To-Xpublish/blob/6dfeec3b56f43c81a881f6191b205c7b1aa22dd9/src/catalog_to_xpublish/server_functions.py#L130) (which for a STAC catalog is [this object method](https://github.com/xpublish-experiments/Catalog-To-Xpublish/blob/6dfeec3b56f43c81a881f6191b205c7b1aa22dd9/src/catalog_to_xpublish/searchers/stac_search.py#L124)) is struggling a bit. On my system it took a little under 3 minutes to parse 100 endpoints, then an additional 5 minutes to get to 200. I'll work on getting some profiling running on this code so we can better identify where the bottle neck in that method is. This seems like the likely culprit for the timeout you reported though. 

We could also just tell gunicorn to wait longer before killing unresponsive worker, but at these runtimes for just 200 endpoints this is refactor territory. I don't know how big the USGS STAC catalog is but I'm guessing it's at least a couple thousand records; [CPEP](https://code.usgs.gov/wma/nhgf/stac/-/tree/main/catalog/cprep?ref_type=heads) might be that alone!

**Comment by sjordan29** [comment]
Thanks for digging into that! @kieranbartels dug into the STAC and there are 418 total "children" (zarr files) in the STAC (297 are cprep).

**Comment by ptomasula** [comment]
@sjordan29 @aufdenkampe 
Here are the results from my initial profiling. 
<img width="686" alt="image" src="https://github.com/xpublish-experiments/Catalog-To-Xpublish/assets/31142705/a73ef792-1510-4d99-8c74-4733cb3e7daf">
From this we can see two bottlenecks. The first, and one that I solved with commit [f68df03](https://github.com/xpublish-experiments/Catalog-To-Xpublish/commit/f68df03f9d943996aa04e45563806c917015342e), is related to copying a catalogs assets prior to iterating over them. We can access the assets directly and avoid the costly copy commands. 

The second bottleneck is related to this [IteratorHandler](https://github.com/xpublish-experiments/Catalog-To-Xpublish/blob/6dfeec3b56f43c81a881f6191b205c7b1aa22dd9/src/catalog_to_xpublish/searchers/stac_search.py#L22) which is [instantiated here](https://github.com/xpublish-experiments/Catalog-To-Xpublish/blob/6dfeec3b56f43c81a881f6191b205c7b1aa22dd9/src/catalog_to_xpublish/searchers/stac_search.py#L148). This one is a little trickier to resolve. The [`catalog.get_children`](https://pystac.readthedocs.io/en/stable/_modules/pystac/catalog.html#Catalog.get_collections) method returns an Iterable. If we dig into the profiling a bit further we can see that the bulk of time spent during iteration is in HTTP requests.
<img width="691" alt="image" src="https://github.com/xpublish-experiments/Catalog-To-Xpublish/assets/31142705/49bb2281-7eb2-4db6-b55b-62095b93afba">

There is probably a way to squeak out additional performance like using an async or multithreading approach to handle that iteration concurrently, but I'd want to do a little more thinking through that. I'm hesitant to just throw concurrency into this code base, especially given the recursive implementation here. It could probably work but it sure feels like a code smell to me.

**Comment by ptomasula** [comment]
Ok I have done a little more reading on this and two observations. 
1) There is likely just some general limit on how quickly links in the STAC catalog can be resolved (i.e. the time it takes to make all those HTTP requests). I'm not sure refinements to the code base will get us much better performance (unless we implement some alternative to [pystac](https://pystac.readthedocs.io/en/stable/index.html)). There is a [`fully_resolve`](https://pystac.readthedocs.io/en/stable/_modules/pystac/catalog.html#Catalog.fully_resolve) method in a pystac Catalog object; if I call that prior to running any of the subsequent code with the iterators, the downstream code using the Catalog runs nearly instantaneously. The catch being that the ~2 minutes is now spent on the `fully_resolve` command instead of resolving them when they are encountered for the first time by the generators.
2) pystac catalogs include a [walk](https://pystac.readthedocs.io/en/stable/_modules/pystac/catalog.html#Catalog.walk) method that seems to me like it would do the same iterating the code is currently doing but without the harder to debug recursive approach. It could be worth implement this approach to improve readability and maintainability, but I expect the performance would be comparable.

**Comment by sjordan29** [comment]
Thanks for digging in, Paul. I just played around with the walk method for building the EDR config a little bit and I don't think it would be a very heavy lift to implement in Catalog-To-Xpublish. I'm not observing any noticeable speedups as you guessed, but definitely seems easier to understand. Perhaps on the wish-list for July or next year!

Sounds like this is as fast as we can get it with a light lift. Sounds like next steps will be:
- In Catalog-To-Xpublish
  - Merge your branch to main in this repo 
  - Issue a release
  - Is it worth opening an issue to explore the use of the `walk` method?
- In xpublish-builder
  - Update `environment.yml` to reference the latest release of this repo
  - Tell gunicorn to wait longer before killing unresponsive worker -- assuming this is something we'd add to the `entrypoint.sh` file there?

**Comment by ptomasula** [comment]
> Thanks for digging in, Paul. I just played around with the walk method for building the EDR config a little bit and I don't think it would be a very heavy lift to implement in Catalog-To-Xpublish. I'm not observing any noticeable speedups as you guessed, but definitely seems easier to understand. Perhaps on the wish-list for July or next year!
> 
> Sounds like this is as fast as we can get it with a light lift. Sounds like next steps will be:
> 
> * In Catalog-To-Xpublish
>   
>   * Merge your branch to main in this repo
>   * Issue a release
>   * Is it worth opening an issue to explore the use of the `walk` method?
> * In xpublish-builder
>   
>   * Update `environment.yml` to reference the latest release of this repo
>   * Tell gunicorn to wait longer before killing unresponsive worker -- assuming this is something we'd add to the `entrypoint.sh` file there?

Thanks @sjordan29, I opened up a [PR](https://github.com/xpublish-experiments/Catalog-To-Xpublish/pull/16) to merge the change in and new [issue](https://github.com/xpublish-experiments/Catalog-To-Xpublish/issues/17) related to walk. I can also make the relevant changes to the builder repository.
